name: assignment-test
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "*"
jobs:
  unit-test:
    container: cuaesd/aesd-autotest:assignment6
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set execute permissions for script
        run: chmod +x ./unit-test.sh
      - name: Run unit test
        run: ./unit-test.sh
  full-test:
    container: cuaesd/aesd-autotest:assignment6
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set execute permissions for script
        run: chmod +x ./full-test.sh
      - name: Run full test
        run: ./full-test.sh
